name: ipn_mobile_app
description: A new Flutter project.

publish_to: 'none'

handlers:
- url: /.*
  http_headers:
    Access-Control-Allow-Origin: "*"
version: 2.0.4
dependency_overrides:
  image: ^4.0.17

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.1
  flutter_app_badger: ^1.5.0 
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.4
  googleapis: ^12.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  youtube_explode_dart: ^1.10.3
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4 
  csv: ^5.0.0
  youtube_api: ^1.0.4
  firebase_messaging: ^14.6.1 
  flutter_local_notifications: ^16.3.2
  shared_preferences: ^2.1.1
  local_auth: ^2.1.6
  profanity_filter: ^2.0.0
  flutter_secure_storage: ^9.0.0
  flutter_html: ^3.0.0-beta.1
  csc_picker: ^0.2.7
  video_player: ^2.6.1
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0
  dotenv: ^4.2.0
  provider: ^6.0.5
  intl: ^0.18.1
  chewie: ^1.5.0
  firebase_storage: ^11.2.2
  pod_player: ^0.2.0
  firebase_app_check: ^0.2.1+13
  font_awesome_flutter: ^10.4.0
  firebase_analytics: ^10.4.2
  flutter_svg: ^2.0.6
  cloud_firestore: ^4.7.0
  firebase_core: ^2.13.0
  cached_network_image: ^3.1.0
  firebase_auth: ^4.6.0
  add_2_calendar: ^3.0.1
  universal_html: ^2.2.1
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_in_app_messaging: ^0.7.3+3
  android_intent_plus: ^4.0.1
  package_info_plus: ^5.0.1
  flutter_linkify: ^6.0.0
  agora_chat_sdk: ^1.2.0
  google_fonts: ^4.0.4
  flutter_neumorphic_plus: ^3.3.0
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  flutter_native_image: ^0.0.6
  path: '>=1.8.3 <2.0.0'
  flutter_riverpod: ^2.4.10
  custom_keyboard: ^1.0.2
  permission_handler: ^11.3.0
  file_picker: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_form_builder: ^9.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  
flutter_native_splash:
  image: images/App Launcher 2.png
  color: "#664FA1"
  fill: false
  web: false

flutter:
  uses-material-design: true
  assets:
    - images/IPN logo Icon.png
    - images/App Launcher.png
    - images/Whte Logo Icon.png
    - images/Whte Logo Variation.png
    - images/The IPN Logo.png
    - assets/privacy_policy.html
    - .env
    - images/Whte Logo Variation 2.png
    - images/Whte Logo Variation.svg
    - images/app_store.png
    - images/google_play.png
    - images/ipn_community_image.png
    - images/ipn_labs_image.png
    - assets/walkthrough.mp4
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "images/App Launcher 2.png"
    min_sdk_android: 21 
    adaptive_icon_background: "#664FA1"
    adaptive_icon_foreground: "images/App Launcher 2.png"